### ISSUE TITLE
Guide to setup ssl certification.

### ISSUE THREAD

**Issue by dustiarmor** [wemove/read2burn#6]
How can I setup a ssl connection?

**Comment by peov** [comment]
Either require https in app.js and switch port to 443 (otherwise browsers will give you an error), or run behind a proxy that routes :443 to http://127.0.0.1:3300
If in docker, expose 3300 is already in Dockerfile (would need to be changed as well) and when using docker run also make sure to map the ports accordingly.

**Comment by joachimmueller** [comment]
I suggest to run the app behind a proxy that terminates the TLS connection. Supporting TLS certificates is beyond this project.
